name: main-pipeline
on: [push]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout
      - name: compile
        run: mvn clean compile
      - name: test
        run: mvn test
      - name: build artifact
        run: mvn package